deploy:
  provider: heroku
  api_key:
    secure: D/k3k49o2hy9Vlug3kXgoBjWqqhJLIdeXSQ+tsvmjVCv9FLDzu5+naHswi6k25KNWwvLOpOjBHCbiYv8kS1vSLejpSJP62YJ20UWYlasLGl3v+WTC0T73V+RlaE5Iv3WwbgVxNxwRbnitc08QM2tljmWdgmCVrlf8Eu2o4yv0SoLTCXdrhJ15T9YeX1eCdaUPfJD3I5EgHAAidp6LCHzROpFdaDCUXDEuNXAmgioUeq2dJ0Ru9xvOulFprNDkS+nsYz185U5uc/PdcL6RwPOAtUdMdp5rHhoiNtqxFzFDW8Pd88KR5W3TPocemHiWSVaWLQYIjkmFTTZiHZ6vLOBVsD9jG244shjtl1/UsLqG02rhSSBq8OMK8D8pXyZ+THQfuGuMJOBjEqY6xwvGPU9yXqAyXePcDGn9ZFTOSytgoUTbuThXr68kVblUwp4cOC6G08gW/97ExKZEYbvtkpLaGgN2vmj0spf3zbgqnfLcwzVdNwM1ZPshO2vt+IG4IIyZ1ecllAEkQ+QJfmMhB6XNh1DDW7sqp84VZYQdof2q1H9fRvVfkm3QIhuR09W4C/HhjKVkP/F9zYoYQNa+a3Txl1gO8pwQgysXzVmZFPxeTDl9DKFo7unh7XvqgJWn8mywGk3XMHl/Ur0vStjoweUkqKkZjdogU3bYtCfN7b8OCk=
  app: 'yes'
  on:
    repo: jayexxd/mixpay
